const fondos = [
  {
    nombre: "Crea y Valida",
    url: "https://www.corfo.cl/sites/cpp/convocatorias/crea_y_valida_2025",
    fechaInicio: "7-2-2025",
    fechaCierre: "13-5-2025",
    plataforma: "CORFO",
  },
  {
    nombre: "Innova Región",
    url: "https://www.corfo.cl/sites/cpp/convocatorias/innova_region_con_foco_en_sostenibilidad",
    fechaInicio: "7-2-2025",
    fechaCierre: "16-4-2025",
    plataforma: "CORFO",
  },
  {
    nombre: "Investigación Tecnológica IDeA 2025",
    url: "https://anid.cl/concursos/concurso-de-investigacion-tecnologica-idea-2025/",
    fechaInicio: "2-2-2025",
    fechaCierre: "20-03-2025",
    plataforma: "ANID",
  },
  {
    nombre: "FONIS 2025",
    url: "https://anid.cl/concursos/proyectos-de-investigacion-y-desarrollo-en-salud-fonis-2025/",
    fechaInicio: "16-01-2025",
    fechaCierre: "24-4-2025",
    plataforma: "ANID",
  },
  {
    nombre: "Equip. Científico y Tecnológico Mediano",
    url: "https://anid.cl/concursos/concurso-de-equipamiento-cientifico-y-tecnologico-mediano-2025/",
    fechaInicio: "27-2-2025",
    fechaCierre: "6-5-2025",
    plataforma: "ANID",
  },
  {
    nombre: "Anillo de Investigación en Áreas Temáticas",
    url: "https://anid.cl/concursos/concurso-anillos-de-investigacion-en-areas-tematicas-especificas-2025/",
    fechaInicio: "28-2-2025",
    fechaCierre: "24-4-2025",
    plataforma: "ANID",
  },
  {
    nombre: "FIC-R 2025",
    url: "http://www.frpd.gobiernovalparaiso.cl/concursos.php",
    fechaInicio: "3-3-2025",
    fechaCierre: "11-4-2025",
    plataforma: "GORE",
  },
  ////////
  {
    nombre: "Viraliza (STEM, Descarbonización, H2V)",
    url: "https://www.corfo.cl/sites/cpp/inf/viraliza",
    fechaInicio: "3-3-2025",
    fechaCierre: "11-4-2025",
    plataforma: "GORE",
  },
  {
    nombre: "Potencia",
    url: "https://www.corfo.cl/sites/cpp/inf/potencia",
    fechaInicio: "1-6-2025",
    fechaCierre: "30-7-2025",
    plataforma: "GORE",
  },
  {
    nombre: "Expande Intermediado",
     url: "https://www.corfo.cl/sites/cpp/convocatorias/expande",
    fechaInicio: "1-6-2025",
    fechaCierre: "30-7-2025",
    plataforma: "GORE",
   },
   { nombre: "Invierte", 
    url: "https://www.corfo.cl/sites/cpp/inf/invierte",
    fechaInicio: "1-8-2025",
    fechaCierre: "30-9-2025",
    plataforma: "GORE",},
   {
     nombre: "Viraliza Eventos",
     url: "https://www.corfo.cl/sites/cpp/inf/viraliza",
      fechaInicio: "1-9-2025",
      fechaCierre: "30-10-2025",
      plataforma: "GORE",
     
   },
   { nombre: "VIU 2025", url: "https://anid.cl/concursos/concurso-viu-2025/",
    fechaInicio: "1-3-2025",
    fechaCierre: "30-4-2025",
    plataforma: "ANID",
    },
   {
     nombre: "Desafíos Públicos 2025",
     url: "https://anid.cl/concursos/desafios-publicos-2025/",
      fechaInicio: "1-5-2025",
      fechaCierre: "30-7-2025",
      plataforma: "ANID",
   },
   {
     nombre: "Startup Ciencia 2026",
     url: "https://anid.cl/concursos/startup-ciencia-2026/",
      fechaInicio: "1-7-2025",
      fechaCierre: "30-9-2025",
      plataforma: "ANID",},
  {
     nombre: "Concurso IDeA I+D 2026",
     url: "https://anid.cl/concursos/concurso-idea-id-2026/",
      fechaInicio: "1-7-2025",
      fechaCierre: "30-9-2025",
      plataforma: "ANID",},
   {
     nombre: "IDeA I+D Tec. Avanzadas 2026",
     url: "https://anid.cl/concursos/concurso-idea-id-tecnologias-avanzadas-2026/",
      fechaInicio: "1-9-2025",
      fechaCierre: "30-11-2025",
      plataforma: "ANID",},
   {
     nombre: "Investigación Tecnológica IDeA 2026",
     url: "https://anid.cl/concursos/concurso-de-investigacion-tecnologica-idea-2026/6",
      fechaInicio: "1-11-2025",
      fechaCierre: "30-12-2025",
      plataforma: "ANID",},
   {
     nombre: "Anillos Regulares de Tecnología 2025",
     url: "https://anid.cl/concursos/concurso-anillos-regulares-de-tecnologia-2025/",
      fechaInicio: "1-2-2025",
      fechaCierre: "30-4-2025",
      plataforma: "ANID",},
];

export default fondos;
